"""initial schema

Revision ID: dd89d230580e
Revises: 
# Create Date: 2026-03-28 12:21:57.604324

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd89d230580e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_costs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.String(length=10), nullable=False),
    sa.Column('period_end', sa.String(length=10), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('synced_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', name='uq_monthly_year_month')
    )
    op.create_table('sync_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.String(length=30), nullable=False),
    sa.Column('finished_at', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('months_synced', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('aws_profile', sa.String(length=100), nullable=True),
    sa.Column('aws_region', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_costs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('monthly_cost_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=200), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('usage_type', sa.Text(), nullable=True),
    sa.Column('synced_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['monthly_cost_id'], ['monthly_costs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('monthly_cost_id', 'service_name', name='uq_service_monthly_name')
    )
    op.create_index('ix_service_costs_monthly_cost_id', 'service_costs', ['monthly_cost_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_service_costs_monthly_cost_id', table_name='service_costs')
    op.drop_table('service_costs')
    op.drop_table('sync_logs')
    op.drop_table('monthly_costs')
    # ### end Alembic commands ###
