"""add_resource_fields_to_notes

Revision ID: de594280e586
Revises: b10718e9dc1e
Create Date: 2026-03-28 22:18:03.431690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de594280e586'
down_revision: Union[str, Sequence[str], None] = 'b10718e9dc1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_notes', sa.Column('resource_id', sa.String(length=500), nullable=True))
    op.add_column('service_notes', sa.Column('resource_name', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_notes', 'resource_name')
    op.drop_column('service_notes', 'resource_id')
    # ### end Alembic commands ###
